export const STATE_FETCH_SUCCESS = 'STATE_FETCH_SUCCESS';
export const STATE_FETCH_FAILED = 'STATE_FETCH_FAILED'
export const PARTICULAR_STATE_SUCCESS = 'PARTICULAR_STATE_SUCCESS'
export const PARTICULAR_STATE_FAILED = 'PARTICULAR_STATE_FAILED'

export const DETAILS_FETCH_SUCCESS = 'DETAILS_FETCH_SUCCESS';
export const DETAILS_FETCH_FAILED = 'DETAILS_FETCH_FAILED';
export const PARTICULAR_DETAILS_SUCCESS = 'PARTICULAR_DETAILS_SUCCESS'
export const PARTICULAR_DETAILS_FAILED = 'PARTICULAR_DETAILS_FAILED'
