export const STATE_FETCH_SUCCESS = 'STATE_FETCH_SUCCESS';
export const STATE_FETCH_FAILED = 'STATE_FETCH_FAILED'
export const PARTICULAR_STATE_SUCCESS = 'PARTICULAR_STATE_SUCCESS'
export const PARTICULAR_STATE_FAILED = 'PARTICULAR_STATE_FAILED'

export const DETAILS_FETCH_SUCCESS = 'DETAILS_FETCH_SUCCESS';
export const DETAILS_FETCH_FAILED = 'DETAILS_FETCH_FAILED';
export const PARTICULAR_DETAILS_SUCCESS = 'PARTICULAR_DETAILS_SUCCESS';
export const PARTICULAR_DETAILS_FAILED = 'PARTICULAR_DETAILS_FAILED';
export const DETAILS_DANGER_SUCCESS = 'DETAILS_DANGER_SUCCESS'
export const DETAILS_DANGER_FAILED = 'DETAILS_DANGER_FAILED'

export const DRUG_FETCH_SUCCESS = 'DRUG_FETCH_SUCCESS';
export const DRUG_FETCH_FAILED = 'DRUG_FETCH_FAILED';
export const DRUG_BYID_SUCCESS = 'DRUG_BYID_SUCCESS'
export const DRUG_BYID_FAILED = 'DRUG_BYID_FAILED'
export const DRUG_ADD_SUCCESS = 'DRUG_ADD_SUCCESS'
export const DRUG_ADD_FAILED = 'DRUG_ADD_FAILED'

export const PROTEIN_ADD_SUCCESS = 'PROTEIN_ADD_SUCCESS';
export const PROTEIN_ADD_FAILED = 'PROTEIN_ADD_FAILED';
export const PROTEIN_FETCH_SUCCESS = 'PROTEIN_FETCH_SUCCESS';
export const PROTEIN_FETCH_FAILED = 'PROTEIN_FETCH_FAILED';
export const PROTEIN_ID_SUCCESS = 'PROTEIN_ID_SUCCESS';
export const PROTEIN_ID_FAILED = 'PROTEIN_ID_FAILED';

export const ADD_GENE_SUCCESS = 'ADD_GENE_SUCCESS';
export const ADD_GENE_FAILED = 'ADD_GENE_FAILED';
export const FETCH_GENE_SUCCESS = 'FETCH_GENE_SUCCESS';
export const FETCH_GENE_FAILED = 'FETCH_GENE_FAILED';
export const GENE_ID_SUCCESS = 'GENE_ID_SUCCESS'
export const GENE_ID_FAILED = 'GENE_ID_FAILED'







